// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXWdJtYjRe6DwOzXqP_e1RDpRsnUqMjJ4',
    appId: '1:300457655065:web:353a80b1c9b0bb04102388',
    messagingSenderId: '300457655065',
    projectId: 'akilli-kiyafet-uygulamasi',
    authDomain: 'akilli-kiyafet-uygulamasi.firebaseapp.com',
    storageBucket: 'akilli-kiyafet-uygulamasi.firebasestorage.app',
    measurementId: 'G-VKRH2KY30E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1oTyBYgauY-jOpkisayeCntIpDfgWIw',
    appId: '1:300457655065:android:2e07bef48ef8191f102388',
    messagingSenderId: '300457655065',
    projectId: 'akilli-kiyafet-uygulamasi',
    storageBucket: 'akilli-kiyafet-uygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfgalycor4UARNNfU5EO9X9ukaKm7_As',
    appId: '1:300457655065:ios:a95d3a812109a82a102388',
    messagingSenderId: '300457655065',
    projectId: 'akilli-kiyafet-uygulamasi',
    storageBucket: 'akilli-kiyafet-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.akilliKiyafetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfgalycor4UARNNfU5EO9X9ukaKm7_As',
    appId: '1:300457655065:ios:a95d3a812109a82a102388',
    messagingSenderId: '300457655065',
    projectId: 'akilli-kiyafet-uygulamasi',
    storageBucket: 'akilli-kiyafet-uygulamasi.firebasestorage.app',
    iosBundleId: 'com.example.akilliKiyafetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXWdJtYjRe6DwOzXqP_e1RDpRsnUqMjJ4',
    appId: '1:300457655065:web:1c648dcfe6a6ea35102388',
    messagingSenderId: '300457655065',
    projectId: 'akilli-kiyafet-uygulamasi',
    authDomain: 'akilli-kiyafet-uygulamasi.firebaseapp.com',
    storageBucket: 'akilli-kiyafet-uygulamasi.firebasestorage.app',
    measurementId: 'G-BBRQ7MTPM9',
  );

}